title: Blog of Hans
description: This is a blog.
baseurl: /blog
url: https://hans5958.github.io
permalink: /:title

author: Hans5958
twitter: "@Hans5958"
copyright_year: 2023
repository: https://github.com/Hans5958/blog

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github
  - draft_temp

livereload: true
markdown: CommonMarkGhPages
future: true

plugins:
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-commonmark-ghpages
  - jekyll-redirect-from   
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-git_metadata
  - jekyll-minifier
  - jekyll-autoprefixer
  - jekyll-toc

jekyll-archives:
  enabled: 
    - year
    - month
    - tags
    - categories
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tag/:name/
    category: /category/:name/

sass:
  # sass_dir: assets/_sass
  style: compressed

commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  sort_reverse: true
  title: ':title - page :num'

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true

autoprefixer:
  browsers:
  - ">= 1%"
  - last 1 major version
  - not dead
  - Chrome >= 60
  - Firefox >= 60
  - Edge >= 16
  - iOS >= 10
  - Safari >= 10
  - Android >= 6
  - not Explorer <= 11

jekyll-minifier:
  uglifier_args:
    harmony: true

toc:
  min_level: 1
  max_level: 7
  list_class: toc-sub
  sublist_class: toc-sublist