title: "Blog of Hans"
email: ""
description: "This is a blog."
baseurl: ""
url: ""
permalink: /:year/:month/:day/:title

markdown: CommonMark

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github
  - import
  
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled: 
    - year
    - month
    - tags
    - categories
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tag/:name/
    category: /category/:name/

sass:
  # sass_dir: assets/_sass
  style: compressed

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  sort_reverse: true
  title: ':title - page :num'