title: Blog of Hans
description: This is a blog.
baseurl: /blog
url: https://hans5958.github.io
permalink: /:year/:month/:day/:title

author: Hans5958
twitter: "@Hans5958"
copyright_year: 2021
repository: https://github.com/Hans5958/blog

markdown: CommonMarkGhPages

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github
  - draft_temp

livereload: true

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-git_metadata

jekyll-archives:
  enabled: 
    - year
    - month
    - tags
    - categories
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tag/:name/
    category: /category/:name/

sass:
  # sass_dir: assets/_sass
  style: compressed

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  sort_reverse: true
  title: ':title - page :num'

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

jekyll-minifier:
  uglifier_args:
    harmony: true
